//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zmkContext : DbContext
    {
        public zmkContext()
            : base("name=zmkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InstrumentSet> InstrumentSet { get; set; }
        public virtual DbSet<JobTitleSet> JobTitleSet { get; set; }
        public virtual DbSet<LaborObjectsSet> LaborObjectsSet { get; set; }
        public virtual DbSet<ManufacturingStepsSet> ManufacturingStepsSet { get; set; }
        public virtual DbSet<ProjectSet> ProjectSet { get; set; }
        public virtual DbSet<TechOpsSet> TechOpsSet { get; set; }
        public virtual DbSet<TimeNormSet> TimeNormSet { get; set; }
        public virtual DbSet<TPSet> TPSet { get; set; }
        public virtual DbSet<WorkTypeSet> WorkTypeSet { get; set; }
    }
}
